#define SIMB_LSHIFT     (char)171
#define SIMB_GRADO      (char)176
#define SIMB_MASMENOS   (char)177
#define SIMB_MICRO      (char)181
#define SIMB_RSHIFT     (char)187
#define SIMB_1CUARTO    (char)188
#define SIMB_1MEDIO     (char)189
#define SIMB_3CUARTOS   (char)190
#define SIMB_DIAMETRO   (char)216
#define SIMB_BETA       (char)223
#define SIMB_ENIE       (char)241
#define SIMB_DIVIDIDO   (char)247